/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.7 */
/* Wed May 10 22:11:06 2023 */

/* parameterized module instance */
PLL_DSP __ (.CLKI( ), .CLKOP( ));
