/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Sun Jun 11 17:19:30 2023 */

/* parameterized module instance */
PLL_DSP __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
