/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Thu May 18 09:04:54 2023 */

/* parameterized module instance */
PLL_DSP __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
