/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.8 */
/* Thu Sep 23 01:31:06 2021 */

/* parameterized module instance */
IDDR __ (.alignwd( ), .clkin( ), .ready( ), .sclk( ), .start( ), 
    .sync_clk( ), .sync_reset( ), .datain( ), .q( ));
