/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.7 */
/* Mon Jan 03 15:01:34 2022 */

/* parameterized module instance */
PLL_SerDes __ (.CLKI( ), .PHASESEL( ), .PHASEDIR( ), .PHASESTEP( ), 
    .PHASELOADREG( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .CLKOS3( ), 
    .LOCK( ));
