/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 1.6 */
/* Fri May 12 16:09:19 2023 */

/* parameterized module instance */
Dummy_slice __ (.CLK0( ), .CE0( ), .RST0( ), .AA( ), .AB( ), .BA( ), 
    .BB( ), .C( ), .AMuxsel( ), .BMuxsel( ), .CMuxsel( ), .Opcode( ), 
    .Cin( ), .SignCin( ), .Result( ), .SignR( ), .EQZ( ), .EQZM( ), 
    .EQOM( ), .EQPAT( ), .EQPATB( ), .OVER( ), .UNDER( ), .SROA( ), 
    .SROB( ));
